[project]
name = "iris"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.12.0",
    "gradio>=6.0.1",
    "huggingface_hub>=0.20.0",
    "loguru>=0.7.3",
    "torch>=2.9.1",
    "transformers>=4.57.3",
]
