[project]
name = "iris"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=6.0.1",
    "llama-cpp-python>=0.2.0",
    "huggingface_hub>=0.20.0",
]
